### PUT request from not-post-owner user
PUT http://localhost:8080/api/posts/reactions/
    6c84fbae-12c4-11ec-82a8-0242ac130003?
    reactionType=LIKE
UserId: 6c84fb99-12c4-11ec-82a8-0242ac130003

### PUT request from not-post-owner user
PUT http://localhost:8080/api/posts/reactions/
    6c84fbae-12c4-11ec-82a8-0242ac130003?
    reactionType=HA_HA
UserId: 6c84fb99-12c4-11ec-82a8-0242ac130003

### PUT request from post owner
PUT http://localhost:8080/api/posts/reactions/
    6c84fbae-12c4-11ec-82a8-0242ac130003?
    reactionType=LOVE
UserId: 6c84fb96-12c4-11ec-82a8-0242ac130003