### delete my message
DELETE http://localhost:8084/api/chat/6c84fbad-12c4-11ec-82a8-0242ac130003
Authorization: Bearer Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Yzg0ZmI5NS0xMmM0LTExZWMtODJhOC0wMjQyYWMxMzAwMDMiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.k3sedckyNF1v0i3QTgGyh3MrxzgqMDVs043zB5X34pY

### delete same message again (error, already deleted)
DELETE http://localhost:8084/api/chat/6c84fbad-12c4-11ec-82a8-0242ac130003
Authorization: Bearer Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Yzg0ZmI5NS0xMmM0LTExZWMtODJhOC0wMjQyYWMxMzAwMDMiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.k3sedckyNF1v0i3QTgGyh3MrxzgqMDVs043zB5X34pY


### delete not my message (error, message not found)
DELETE http://localhost:8084/api/chat/6c84fbad-12c4-11ec-82a8-0242ac130010
Authorization: Bearer Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Yzg0ZmI5NS0xMmM0LTExZWMtODJhOC0wMjQyYWMxMzAwMDMiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.k3sedckyNF1v0i3QTgGyh3MrxzgqMDVs043zB5X34pY
