server:
  port: 8081

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

---

spring:
  mvc:
    log-request-details: true # for debugging

  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

---

spring:
  config:
    activate:
      on-profile: dev

  mvc:
    log-request-details: true # for debugging

  datasource:
    url: jdbc:postgresql://user-db-service:5432/user_db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
