x-service: &service
  environment:
    - SPRING_PROFILES_ACTIVE=dev

x-db: &db
  image: postgres:16.0-alpine
  restart: always
  healthcheck:
    test: pg_isready -U postgres
    interval: 10s
    timeout: 5s
    retries: 5

x-db-env: &db-env
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

services:
  user_service:
    <<: *service
    build: user-service
    ports:
      - 8081:8081
    networks:
      - net_userDB_userServ
    depends_on:
      user_db_service:
        condition: service_healthy

  user_db_service:
    <<: *db
    environment:
      <<: *db-env
      POSTGRES_DB: user_db
    volumes:
      - vol_user_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - net_userDB_userServ

  post_service:
    <<: *service
    build: post-service
    ports:
      - 8082:8082
    networks:
      - net_postDB_postServ
    depends_on:
      post_db_service:
        condition: service_healthy

  post_db_service:
    <<: *db
    environment:
      <<: *db-env
      POSTGRES_DB: post_db
      PGPORT: 5433
    volumes:
      - vol_post_db:/var/lib/postgresql/data
    ports:
      - 5433:5433
    networks:
      - net_postDB_postServ

networks:
  net_postDB_postServ:
  net_userDB_userServ:
  net_postServ_userServ:

volumes:
  vol_post_db:
  vol_user_db: