x-service: &service
  environment:
    - SPRING_PROFILES_ACTIVE=dev

x-db: &db
  image: postgres:16.0-alpine
  restart: always
  healthcheck:
    test: pg_isready -U postgres
    interval: 10s
    timeout: 5s
    retries: 5

x-db-env: &db-env
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

services:
  user_service:
    <<: *service
    build: user-service
    ports:
      - 8081:8081
    networks:
      - network_user_db_service
    depends_on:
      user_db_host:
        condition: service_healthy

  user_db_host:
    <<: *db
    environment:
      <<: *db-env
      POSTGRES_DB: user_db
    volumes:
      - user_db_host:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - network_user_db_service

  post_service:
    <<: *service
    build: post-service
    ports:
      - 8082:8082
    networks:
      - network_post_db_service
    depends_on:
      post_db_host:
        condition: service_healthy

  post_db_host:
    <<: *db
    environment:
      <<: *db-env
      POSTGRES_DB: post_db
      PGPORT: 5433
    volumes:
      - post_db_host:/var/lib/postgresql/data
    ports:
      - 5433:5433
    networks:
      - network_post_db_service

networks:
  network_user_db_service:
  network_post_db_service:

volumes:
  user_db_host:
  post_db_host: