

POST http://localhost:8443/realms/users-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username = test &
password = test &
client_id = frontend-web &
grant_type = password

> {% client.global.set("auth_token", response.body["access_token"]) %}
###

POST http://localhost:8080/api/posts
Authorization: Bearer {{auth_token}}
UserId: 6c84fb9b-12c4-11ec-82a8-0242ac1300
Content-Type: application/json

{
  "content": "Siema"
}
