server:
  port: 8080
  ssl:
    key-store-type: JKS
    key-store: classpath:gateway.jks
    key-store-password: gateway
    key-store-provider: SUN
    key-alias: gateway
    trust-store: classpath:gateway_truststore.jks
    trust-store-password: gateway
    trust-store-type: JKS

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

app:
  cors:
    allowed-origins: https://localhost:4200
  jwt:
    keycloak: https://keycloak-service:8443
    realm: SpeakApp
    issuer-uri: https://localhost:8443/realms/${app.jwt.realm}
    resource-client-id: SpeakAppClient

spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          trusted-x509-certificates:
            - "classpath:nginx-selfsigned.crt"

  main:
    web-application-type: reactive
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${app.jwt.issuer-uri}
          jwk-set-uri: ${app.jwt.keycloak}/realms/${app.jwt.realm}/protocol/openid-connect/certs
  application:
    name: api-gateway


