logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

app:
  cors:
    allowed-origins: http://localhost:4200
  jwt:
    keycloak: http://keycloak:8443
    realm: users-realm
    issuer-uri: http://localhost:8443/realms/${app.jwt.realm}
    resource-client-id: frontend-web

spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${app.jwt.issuer-uri}
          jwk-set-uri: ${app.jwt.keycloak}/realms/${app.jwt.realm}/protocol/openid-connect/certs
