POST http://localhost:8081/api/users
Content-Type: application/json

{
  "userId": "6c84fb95-12c4-11ec-82a8-0242ac130039",
  "firstName": "Michael",
  "lastName": "Jordan",
  "email": "mj@gmail.com",
  "dateOfBirth": "1999-12-12"
}