server:
  port: 8082

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

---

spring:
  application:
    name: post-service
  config:
    activate:
      on-profile: local

  mvc:
    log-request-details: true # for debugging

  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka //TODO: add discovery client
      # This is the name of the service in docker-compose.yml was localhost:8761/eureka

---

spring:
  config:
    activate:
      on-profile: dev

  sql:
    init:
      platform: postgres
      mode: always
      separator: "^^^ END OF SCRIPT ^^^"

  mvc:
    log-request-details: true # for debugging

  datasource:
    url: jdbc:postgresql://post-db-service:5433/post_db
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true # Very important to include - otherwise loading data.sql file will cause error
